[phases.setup]
nixPkgs = ["python39", "pip", "gcc", "gfortran", "libsndfile"]

[phases.install]
cmds = ["cd Backend && pip install --upgrade pip", "cd Backend && pip install -r requeriment.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"